### PR TITLE
Move the NUsense firmware to the NUcontroller repository.

### PR DESCRIPTION
**Pull request by Claegtun**
### Brief

Adds the NUsense firmware to the Nucontroller repository,

### Context

We are moving the firmware from NUware so that it is better organised.

### CODE REVIEW

**Comment by ysims** [comment]
Are all of these files necessary? I did a quick search and a .gitignore of a stm32 project might look something like 

```
.metadata
.settings
[Rr]elease
[Dd]ebug
.launch
```

**Comment by Claegtun** [comment]
> Are all of these files necessary? I did a quick search and a .gitignore of a stm32 project might look something like
> 
> ```
> .metadata
> .settings
> [Rr]elease
> [Dd]ebug
> .launch
> ```

Yeah, probably not. I tend to just add everything. I will remove them when I get time.

**Comment by Claegtun** [comment]
> Are all of these files necessary? I did a quick search and a .gitignore of a stm32 project might look something like
> 
> ```
> .metadata
> .settings
> [Rr]elease
> [Dd]ebug
> .launch
> ```

Yeah, porbably not. I tend to add everything. I will removed them when I get time.

**Review by JohanneMontano — DISMISSED** [review]
Does this STM32 project need to be cleaned? There are some .cyclo, .su and .d files that don't really need to be in this repo as they are generated during build time, so these files could easily change in the future

**Review by jpptm — CHANGES_REQUESTED** [review]
I just marked the comment from my other account as outdated, but it seems like there are .cyclo, .su and .d files that does not need to be in this pr. Cleaning the STM32 project might be needed to decrease the code volume?

**Review by ysims — APPROVED** [review]

**Review by jpptm — APPROVED** [review]

**Pull request merged**
